In [1]:
from keras.models import Sequential

D:\ruanjian\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [4]:
from keras.layers.core import Dense,Activation

In [5]:
from keras.optimizers import SGD

In [6]:
md1 = Sequential()

In [7]:
md1.add(Dense(50))

In [8]:
md1.add(Activation("sigmoid"))

In [10]:
md1.add(Dense(2))

In [11]:
md1.add(Activation("softmax"))

In [12]:
sgd = SGD(lr=0.01)

In [14]:
md1.compile(loss="mean_squared_error",optimizer=sgd)

In [ ]:
md1.fit(X_)

In [15]:
from keras.models import Sequential  
from keras.layers.core import Dense, Dropout, Activation  
from keras.optimizers import SGD  
from keras.datasets import mnist  
import numpy 
'''
    第一步：选择模型
'''
model = Sequential()
'''
   第二步：构建网络层
'''
model.add(Dense(500,input_shape=(784,))) # 输入层，28*28=784  
model.add(Activation('tanh')) # 激活函数是tanh  
model.add(Dropout(0.5)) # 采用50%的dropout

model.add(Dense(500)) # 隐藏层节点500个  
model.add(Activation('tanh'))  
model.add(Dropout(0.5))

model.add(Dense(10)) # 输出结果是10个类别，所以维度是10  
model.add(Activation('softmax')) # 最后一层用softmax作为激活函数

'''
   第三步：编译
'''
sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True) # 优化函数，设定学习率（lr）等参数  
model.compile(loss='categorical_crossentropy', optimizer=sgd, class_mode='categorical') # 使用交叉熵作为loss函数

'''
   第四步：训练
   .fit的一些参数
   batch_size：对总的样本数进行分组，每组包含的样本数量
   epochs ：训练次数
   shuffle：是否把数据随机打乱之后再进行训练
   validation_split：拿出百分之多少用来做交叉验证
   verbose：屏显模式 0：不输出  1：输出进度  2：输出每次的训练结果
'''
(X_train, y_train), (X_test, y_test) = mnist.load_data() # 使用Keras自带的mnist工具读取数据（第一次需要联网）
# 由于mist的输入数据维度是(num, 28, 28)，这里需要把后面的维度直接拼起来变成784维  
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1] * X_train.shape[2]) 
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1] * X_test.shape[2])  
Y_train = (numpy.arange(10) == y_train[:, None]).astype(int) 
Y_test = (numpy.arange(10) == y_test[:, None]).astype(int)

model.fit(X_train,Y_train,batch_size=200,epochs=50,shuffle=True,verbose=0,validation_split=0.3)
model.evaluate(X_test, Y_test, batch_size=200, verbose=0)

'''
    第五步：输出
'''
print("test set")
scores = model.evaluate(X_test,Y_test,batch_size=200,verbose=0)
print("")
print("The test loss is %f" % scores)
result = model.predict(X_test,batch_size=200,verbose=0)

result_max = numpy.argmax(result, axis = 1)
test_max = numpy.argmax(Y_test, axis = 1)

result_bool = numpy.equal(result_max, test_max)
true_num = numpy.sum(result_bool)
print("")
print("The accuracy of the model is %f" % (true_num/len(result_bool)))

RemoteDisconnected: Remote end closed connection without response

In [18]:
from sklearn import datasets

In [23]:
from sklearn import datasets

bst = datasets.load_boston()

X = bst.data
y = bst.target

In [26]:
X.shape

(506, 13)

In [27]:
y.shape

(506,)

In [ ]:
from keras.models import Sequential  
from keras.layers.core import Dense, Dropout, Activation  
from keras.optimizers import SGD  
from keras.datasets import mnist  
import numpy 
'''
    第一步：选择模型
'''
model = Sequential()
'''
   第二步：构建网络层
'''
model.add(Dense(500,input_shape=(784,))) # 输入层，28*28=784  
model.add(Activation('tanh')) # 激活函数是tanh  
model.add(Dropout(0.5)) # 采用50%的dropout

model.add(Dense(500)) # 隐藏层节点500个  
model.add(Activation('tanh'))  
model.add(Dropout(0.5))

model.add(Dense(10)) # 输出结果是10个类别，所以维度是10  
model.add(Activation('softmax')) # 最后一层用softmax作为激活函数

'''
   第三步：编译
'''
sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True) # 优化函数，设定学习率（lr）等参数  
model.compile(loss='categorical_crossentropy', optimizer=sgd, class_mode='categorical') # 使用交叉熵作为loss函数


In [29]:
import matplotlib.pyplot as plt
from math import sqrt
from matplotlib import pyplot
import pandas as pd
from numpy import concatenate
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.optimizers import Adam
'''
keras实现神经网络回归模型
'''

# 原始数据标准化，为了加速收敛
scaler = MinMaxScaler(feature_range=(0, 1))
X_scaled = scaler.fit_transform(X)
y_scaled = scaler.fit_transform(y)
y = y_scaled
X = X_scaled
 
# 随机拆分训练集与测试集
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.25)
 
# 全连接神经网络
model = Sequential()
input = X.shape[1]
# 隐藏层128
model.add(Dense(128, input_shape=(input,)))
model.add(Activation('relu'))
# Dropout层用于防止过拟合
#model.add(Dropout(0.2))
# 隐藏层128
model.add(Dense(128))
model.add(Activation('relu'))
#model.add(Dropout(0.2))
# 没有激活函数用于输出层，因为这是一个回归问题，我们希望直接预测数值，而不需要采用激活函数进行变换。
model.add(Dense(1))
# 使用高效的 ADAM 优化算法以及优化的最小均方误差损失函数
model.compile(loss='mean_squared_error', optimizer=Adam())
# early stoppping
from keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=50, verbose=2)
# 训练
history = model.fit(train_X, train_y, epochs=300, batch_size=20, validation_data=(test_X, test_y), verbose=2, shuffle=False, callbacks=[early_stopping])
# loss曲线
pyplot.plot(history.history['loss'], label='train')
pyplot.plot(history.history['val_loss'], label='test')
pyplot.legend()
pyplot.show()
# 预测
yhat = model.predict(test_X)
# 预测y逆标准化
inv_yhat0 = concatenate((test_X, yhat), axis=1)
inv_yhat1 = scaler.inverse_transform(inv_yhat0)
inv_yhat = inv_yhat1[:,-1]
# 原始y逆标准化
test_y = test_y.reshape((len(test_y), 1))
inv_y0 = concatenate((test_X,test_y), axis=1)
inv_y1 = scaler.inverse_transform(inv_y0)
inv_y = inv_y1[:,-1]
# 计算 RMSE
rmse = sqrt(mean_squared_error(inv_y, inv_yhat))
print('Test RMSE: %.3f' % rmse)
plt.plot(inv_y)
plt.plot(inv_yhat)
plt.show()


ValueError: Expected 2D array, got 1D array instead:
array=[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 30.3 34.6 34.9 32.9 24.1 42.3 48.5 50.  22.6 24.4 22.5 24.4 20.
 21.7 19.3 22.4 28.1 23.7 25.  23.3 28.7 21.5 23.  26.7 21.7 27.5 30.1
 44.8 50.  37.6 31.6 46.7 31.5 24.3 31.7 41.7 48.3 29.  24.  25.1 31.5
 23.7 23.3 22.  20.1 22.2 23.7 17.6 18.5 24.3 20.5 24.5 26.2 24.4 24.8
 29.6 42.8 21.9 20.9 44.  50.  36.  30.1 33.8 43.1 48.8 31.  36.5 22.8
 30.7 50.  43.5 20.7 21.1 25.2 24.4 35.2 32.4 32.  33.2 33.1 29.1 35.1
 45.4 35.4 46.  50.  32.2 22.  20.1 23.2 22.3 24.8 28.5 37.3 27.9 23.9
 21.7 28.6 27.1 20.3 22.5 29.  24.8 22.  26.4 33.1 36.1 28.4 33.4 28.2
 22.8 20.3 16.1 22.1 19.4 21.6 23.8 16.2 17.8 19.8 23.1 21.  23.8 23.1
 20.4 18.5 25.  24.6 23.  22.2 19.3 22.6 19.8 17.1 19.4 22.2 20.7 21.1
 19.5 18.5 20.6 19.  18.7 32.7 16.5 23.9 31.2 17.5 17.2 23.1 24.5 26.6
 22.9 24.1 18.6 30.1 18.2 20.6 17.8 21.7 22.7 22.6 25.  19.9 20.8 16.8
 21.9 27.5 21.9 23.1 50.  50.  50.  50.  50.  13.8 13.8 15.  13.9 13.3
 13.1 10.2 10.4 10.9 11.3 12.3  8.8  7.2 10.5  7.4 10.2 11.5 15.1 23.2
  9.7 13.8 12.7 13.1 12.5  8.5  5.   6.3  5.6  7.2 12.1  8.3  8.5  5.
 11.9 27.9 17.2 27.5 15.  17.2 17.9 16.3  7.   7.2  7.5 10.4  8.8  8.4
 16.7 14.2 20.8 13.4 11.7  8.3 10.2 10.9 11.   9.5 14.5 14.1 16.1 14.3
 11.7 13.4  9.6  8.7  8.4 12.8 10.5 17.1 18.4 15.4 10.8 11.8 14.9 12.6
 14.1 13.  13.4 15.2 16.1 17.8 14.9 14.1 12.7 13.5 14.9 20.  16.4 17.7
 19.5 20.2 21.4 19.9 19.  19.1 19.1 20.1 19.9 19.6 23.2 29.8 13.8 13.3
 16.7 12.  14.6 21.4 23.  23.7 25.  21.8 20.6 21.2 19.1 20.6 15.2  7.
  8.1 13.6 20.1 21.8 24.5 23.1 19.7 18.3 21.2 17.5 16.8 22.4 20.6 23.9
 22.  11.9].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [35]:
from sklearn import datasets

iris = datasets.load_iris()

X = iris.data
y = iris.target
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.25)

In [36]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.25)

In [37]:
# 全连接神经网络
model = Sequential()
input = X.shape[1]
# 隐藏层128
model.add(Dense(128, input_shape=(input,)))
model.add(Activation('relu'))
# Dropout层用于防止过拟合
#model.add(Dropout(0.2))
# 隐藏层128
model.add(Dense(128))
model.add(Activation('relu'))
#model.add(Dropout(0.2))
# 没有激活函数用于输出层，因为这是一个回归问题，我们希望直接预测数值，而不需要采用激活函数进行变换。
model.add(Dense(1))
# 使用高效的 ADAM 优化算法以及优化的最小均方误差损失函数
model.compile(loss='mean_squared_error', optimizer=Adam())


In [38]:
model.fit(train_X,train_y,nb_epoch=1000,batch_size=10)

D:\ruanjian\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/1000
112/112 [==============================] - 2s 19ms/step - loss: 0.7396
Epoch 2/1000
112/112 [==============================] - 0s 160us/step - loss: 0.1958
Epoch 3/1000
112/112 [==============================] - 0s 151us/step - loss: 0.0814
Epoch 4/1000
112/112 [==============================] - 0s 160us/step - loss: 0.0701
Epoch 5/1000
112/112 [==============================] - 0s 2ms/step - loss: 0.0605
Epoch 6/1000
112/112 [==============================] - 0s 231us/step - loss: 0.0604
Epoch 7/1000
112/112 [==============================] - 0s 178us/step - loss: 0.0561
Epoch 8/1000
112/112 [==============================] - 0s 232us/step - loss: 0.0552
Epoch 9/1000
112/112 [==============================] - 0s 232us/step - loss: 0.0576
Epoch 10/1000
112/112 [==============================] - 0s 169us/step - loss: 0.0492
Epoch 11/1000
112/112 [==============================] - 0s 205us/step - loss: 0.0561
Epoch 12/1000
112/112 [==============================] - 0s 160us/

112/112 [==============================] - 0s 134us/step - loss: 0.0365
Epoch 97/1000
112/112 [==============================] - 0s 151us/step - loss: 0.0361
Epoch 98/1000
112/112 [==============================] - 0s 125us/step - loss: 0.0566
Epoch 99/1000
112/112 [==============================] - 0s 125us/step - loss: 0.0385
Epoch 100/1000
112/112 [==============================] - 0s 134us/step - loss: 0.0350
Epoch 101/1000
112/112 [==============================] - 0s 151us/step - loss: 0.0358
Epoch 102/1000
112/112 [==============================] - 0s 169us/step - loss: 0.0441
Epoch 103/1000
112/112 [==============================] - 0s 187us/step - loss: 0.0433
Epoch 104/1000
112/112 [==============================] - 0s 151us/step - loss: 0.0384
Epoch 105/1000
112/112 [==============================] - 0s 169us/step - loss: 0.0394
Epoch 106/1000
112/112 [==============================] - 0s 178us/step - loss: 0.0360
Epoch 107/1000
112/112 [==============================] - 0s 

112/112 [==============================] - 0s 187us/step - loss: 0.0540
Epoch 191/1000
112/112 [==============================] - 0s 134us/step - loss: 0.0395
Epoch 192/1000
112/112 [==============================] - 0s 134us/step - loss: 0.0456
Epoch 193/1000
112/112 [==============================] - 0s 151us/step - loss: 0.0370
Epoch 194/1000
112/112 [==============================] - 0s 125us/step - loss: 0.0346
Epoch 195/1000
112/112 [==============================] - 0s 134us/step - loss: 0.0356
Epoch 196/1000
112/112 [==============================] - 0s 160us/step - loss: 0.0396
Epoch 197/1000
112/112 [==============================] - 0s 142us/step - loss: 0.0329
Epoch 198/1000
112/112 [==============================] - 0s 169us/step - loss: 0.0309
Epoch 199/1000
112/112 [==============================] - 0s 169us/step - loss: 0.0303
Epoch 200/1000
112/112 [==============================] - 0s 160us/step - loss: 0.0331
Epoch 201/1000
112/112 [==============================] - 

112/112 [==============================] - 0s 142us/step - loss: 0.0281
Epoch 285/1000
112/112 [==============================] - 0s 142us/step - loss: 0.0235
Epoch 286/1000
112/112 [==============================] - 0s 134us/step - loss: 0.0275
Epoch 287/1000
112/112 [==============================] - 0s 116us/step - loss: 0.0291
Epoch 288/1000
112/112 [==============================] - 0s 169us/step - loss: 0.0301
Epoch 289/1000
112/112 [==============================] - 0s 169us/step - loss: 0.0260
Epoch 290/1000
112/112 [==============================] - 0s 196us/step - loss: 0.0284
Epoch 291/1000
112/112 [==============================] - 0s 160us/step - loss: 0.0329
Epoch 292/1000
112/112 [==============================] - 0s 178us/step - loss: 0.0272
Epoch 293/1000
112/112 [==============================] - 0s 133us/step - loss: 0.0243
Epoch 294/1000
112/112 [==============================] - 0s 169us/step - loss: 0.0263
Epoch 295/1000
112/112 [==============================] - 

112/112 [==============================] - 0s 142us/step - loss: 0.0212
Epoch 379/1000
112/112 [==============================] - 0s 134us/step - loss: 0.0314
Epoch 380/1000
112/112 [==============================] - 0s 152us/step - loss: 0.0244
Epoch 381/1000
112/112 [==============================] - 0s 151us/step - loss: 0.0235
Epoch 382/1000
112/112 [==============================] - 0s 142us/step - loss: 0.0204
Epoch 383/1000
112/112 [==============================] - 0s 169us/step - loss: 0.0209
Epoch 384/1000
112/112 [==============================] - 0s 187us/step - loss: 0.0223
Epoch 385/1000
112/112 [==============================] - 0s 151us/step - loss: 0.0212
Epoch 386/1000
112/112 [==============================] - 0s 187us/step - loss: 0.0212
Epoch 387/1000
112/112 [==============================] - 0s 151us/step - loss: 0.0205
Epoch 388/1000
112/112 [==============================] - 0s 160us/step - loss: 0.0224
Epoch 389/1000
112/112 [==============================] - 

112/112 [==============================] - 0s 151us/step - loss: 0.0161
Epoch 472/1000
112/112 [==============================] - 0s 134us/step - loss: 0.0172
Epoch 473/1000
112/112 [==============================] - 0s 160us/step - loss: 0.0174
Epoch 474/1000
112/112 [==============================] - 0s 151us/step - loss: 0.0200
Epoch 475/1000
112/112 [==============================] - 0s 206us/step - loss: 0.0208
Epoch 476/1000
112/112 [==============================] - 0s 134us/step - loss: 0.0163
Epoch 477/1000
112/112 [==============================] - 0s 116us/step - loss: 0.0179
Epoch 478/1000
112/112 [==============================] - 0s 125us/step - loss: 0.0174
Epoch 479/1000
112/112 [==============================] - 0s 125us/step - loss: 0.0158
Epoch 480/1000
112/112 [==============================] - 0s 151us/step - loss: 0.0165
Epoch 481/1000
112/112 [==============================] - 0s 125us/step - loss: 0.0168
Epoch 482/1000
112/112 [==============================] - 

112/112 [==============================] - 0s 134us/step - loss: 0.0141
Epoch 566/1000
112/112 [==============================] - 0s 116us/step - loss: 0.0150
Epoch 567/1000
112/112 [==============================] - 0s 169us/step - loss: 0.0167
Epoch 568/1000
112/112 [==============================] - 0s 116us/step - loss: 0.0166
Epoch 569/1000
112/112 [==============================] - 0s 116us/step - loss: 0.0153
Epoch 570/1000
112/112 [==============================] - 0s 160us/step - loss: 0.0197
Epoch 571/1000
112/112 [==============================] - 0s 142us/step - loss: 0.0151
Epoch 572/1000
112/112 [==============================] - 0s 169us/step - loss: 0.0154
Epoch 573/1000
112/112 [==============================] - 0s 169us/step - loss: 0.0190
Epoch 574/1000
112/112 [==============================] - 0s 205us/step - loss: 0.0166
Epoch 575/1000
112/112 [==============================] - 0s 160us/step - loss: 0.0143
Epoch 576/1000
112/112 [==============================] - 

112/112 [==============================] - 0s 125us/step - loss: 0.0145
Epoch 660/1000
112/112 [==============================] - 0s 160us/step - loss: 0.0143
Epoch 661/1000
112/112 [==============================] - 0s 125us/step - loss: 0.0172
Epoch 662/1000
112/112 [==============================] - 0s 169us/step - loss: 0.0244
Epoch 663/1000
112/112 [==============================] - 0s 142us/step - loss: 0.0151
Epoch 664/1000
112/112 [==============================] - ETA: 0s - loss: 0.012 - 0s 142us/step - loss: 0.0161
Epoch 665/1000
112/112 [==============================] - 0s 214us/step - loss: 0.0154
Epoch 666/1000
112/112 [==============================] - 0s 160us/step - loss: 0.0137
Epoch 667/1000
112/112 [==============================] - 0s 160us/step - loss: 0.0144
Epoch 668/1000
112/112 [==============================] - 0s 151us/step - loss: 0.0154
Epoch 669/1000
112/112 [==============================] - 0s 169us/step - loss: 0.0295
Epoch 670/1000
112/112 [==========

112/112 [==============================] - 0s 116us/step - loss: 0.0252
Epoch 754/1000
112/112 [==============================] - 0s 151us/step - loss: 0.0207
Epoch 755/1000
112/112 [==============================] - 0s 134us/step - loss: 0.0168
Epoch 756/1000
112/112 [==============================] - 0s 116us/step - loss: 0.0139
Epoch 757/1000
112/112 [==============================] - 0s 116us/step - loss: 0.0144
Epoch 758/1000
112/112 [==============================] - 0s 151us/step - loss: 0.0156
Epoch 759/1000
112/112 [==============================] - 0s 116us/step - loss: 0.0131
Epoch 760/1000
112/112 [==============================] - 0s 160us/step - loss: 0.0120
Epoch 761/1000
112/112 [==============================] - 0s 169us/step - loss: 0.0128
Epoch 762/1000
112/112 [==============================] - 0s 169us/step - loss: 0.0141
Epoch 763/1000
112/112 [==============================] - 0s 134us/step - loss: 0.0155
Epoch 764/1000
112/112 [==============================] - 

112/112 [==============================] - 0s 125us/step - loss: 0.0277
Epoch 848/1000
112/112 [==============================] - 0s 125us/step - loss: 0.0230
Epoch 849/1000
112/112 [==============================] - 0s 169us/step - loss: 0.0156
Epoch 850/1000
112/112 [==============================] - 0s 151us/step - loss: 0.0177
Epoch 851/1000
112/112 [==============================] - 0s 125us/step - loss: 0.0168
Epoch 852/1000
112/112 [==============================] - 0s 196us/step - loss: 0.0156
Epoch 853/1000
112/112 [==============================] - 0s 160us/step - loss: 0.0121
Epoch 854/1000
112/112 [==============================] - 0s 169us/step - loss: 0.0131
Epoch 855/1000
112/112 [==============================] - 0s 178us/step - loss: 0.0144
Epoch 856/1000
112/112 [==============================] - 0s 142us/step - loss: 0.0139
Epoch 857/1000
112/112 [==============================] - 0s 178us/step - loss: 0.0116
Epoch 858/1000
112/112 [==============================] - 

112/112 [==============================] - 0s 152us/step - loss: 0.0184
Epoch 942/1000
112/112 [==============================] - 0s 134us/step - loss: 0.0121
Epoch 943/1000
112/112 [==============================] - 0s 125us/step - loss: 0.0121
Epoch 944/1000
112/112 [==============================] - 0s 151us/step - loss: 0.0119
Epoch 945/1000
112/112 [==============================] - 0s 142us/step - loss: 0.0128
Epoch 946/1000
112/112 [==============================] - 0s 125us/step - loss: 0.0148
Epoch 947/1000
112/112 [==============================] - 0s 160us/step - loss: 0.0147
Epoch 948/1000
112/112 [==============================] - 0s 160us/step - loss: 0.0292
Epoch 949/1000
112/112 [==============================] - 0s 178us/step - loss: 0.0191
Epoch 950/1000
112/112 [==============================] - 0s 169us/step - loss: 0.0146
Epoch 951/1000
112/112 [==============================] - 0s 151us/step - loss: 0.0135
Epoch 952/1000
112/112 [==============================] - 

In [47]:
yp = model.predict_classes(test_X)

In [48]:
yp

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0]])

In [49]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [43]:
test_y

array([1, 0, 2, 0, 2, 0, 0, 0, 1, 2, 0, 0, 1, 0, 0, 2, 2, 2, 0, 0, 0, 0,
       1, 0, 2, 2, 1, 2, 2, 2, 1, 1, 2, 0, 1, 0, 0, 0])

In [63]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.preprocessing import LabelEncoder

In [82]:
from sklearn import datasets

iris = datasets.load_iris()

X = iris.data
y = iris.target

# encode class values as integers
encoder = LabelEncoder()
encoded_Y = encoder.fit_transform(y)
# convert integers to dummy variables (one hot encoding)
dummy_y = np_utils.to_categorical(encoded_Y)


from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.25)

In [83]:
from keras.wrappers.scikit_learn import KerasClassifier
# define model structure
def baseline_model():
    model = Sequential()
    model.add(Dense(output_dim=10, input_dim=4, activation='relu'))
    model.add(Dropout(0.2))
    model.add(Dense(output_dim=3, input_dim=10, activation='softmax'))
    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model
estimator = KerasClassifier(build_fn=baseline_model, nb_epoch=40, batch_size=256)

In [84]:
estimator.fit(train_X, train_y)

D:\ruanjian\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=4, activation="relu", units=10)`
  """
D:\ruanjian\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=10, activation="softmax", units=3)`
  import sys


Epoch 1/1
112/112 [==============================] - 1s 7ms/step - loss: 2.1238 - acc: 0.3125


In [85]:
# make predictions
pred = estimator.predict(test_X)

In [86]:
pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [87]:
test_y

array([2, 1, 2, 2, 1, 2, 0, 0, 0, 2, 2, 1, 0, 0, 1, 1, 1, 1, 2, 0, 0, 0,
       2, 2, 1, 2, 0, 0, 1, 1, 2, 0, 1, 0, 1, 2, 0, 2])

In [88]:
init_lables = encoder.inverse_transform(pred)

D:\ruanjian\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [79]:
# inverse numeric variables to initial categorical labels
init_lables = encoder.inverse_transform(pred)

D:\ruanjian\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [80]:
# k-fold cross-validate
seed = 42
np.random.seed(seed)
kfold = KFold(n_splits=10, shuffle=True, random_state=seed)
results = cross_val_score(estimator, X, dummy_y, cv=kfold)

D:\ruanjian\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=4, activation="relu", units=10)`
  """
D:\ruanjian\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=10, activation="softmax", units=3)`
  import sys


Epoch 1/1
15/15 [==============================] - 0s 6ms/step
Epoch 1/1
15/15 [==============================] - 0s 7ms/step
Epoch 1/1
15/15 [==============================] - 0s 10ms/step
Epoch 1/1
15/15 [==============================] - 0s 8ms/step
Epoch 1/1
15/15 [==============================] - 0s 9ms/step
Epoch 1/1
15/15 [==============================] - 0s 10ms/step
Epoch 1/1
15/15 [==============================] - 0s 10ms/step
Epoch 1/1
15/15 [==============================] - 0s 11ms/step
Epoch 1/1
15/15 [==============================] - 0s 12ms/step
Epoch 1/1
15/15 [==============================] - 0s 17ms/step


In [81]:
results

array([0.40000001, 0.53333336, 0.13333334, 0.26666668, 0.26666668,
       0.2       , 0.2       , 0.40000001, 0.33333334, 0.40000001])