In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame
import matplotlib.pyplot as plt
from datetime import datetime
import seaborn as sns
sns.set()

In [5]:
df = pd.read_excel('D:/2018 广东金融学院数学建模第一次模拟(1)/2018 广东金融学院数学建模第一次模拟/附件1.xls')
df.head()

df = df.drop(6329)
df['y'] = df['y'].astype('float')
X = df.loc[:,'x1':'x6'].as_matrix()
y = df.loc[:,'y'].as_matrix()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

D:\ruanjian\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  
D:\ruanjian\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  import sys


In [6]:
df.tail()

Number    y     x1     x2  x3      x4        x5  x6
6324    6325  1.0  63.07  52.74   1  0.4574  0.945349   2
6325    6326  1.0  52.63  43.20   1  0.4574  1.024651   2
6326    6327  1.0  59.05  54.98   1  0.4062  0.793256   1
6327    6328  1.0  74.65  40.46   0  0.3818  1.274419   1
6328    6329  1.0  44.68  52.24   1  0.6660  0.772326   3

In [9]:
print(type(df['x1'][1]))
print(type(df['x2'][1]))
print(type(df['x3'][1]))
print(type(df['x4'][1]))
print(type(df['x5'][1]))
print(type(df['x6'][1]))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.int64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.int64'>


In [10]:
df['y'] = df['y'].astype('float')

In [11]:
X

array([[63.91      , 50.34      ,  0.        ,  0.3662    ,  0.34883721,
         1.        ],
       [61.17      , 37.7       ,  1.        ,  0.5724    ,  1.02790698,
         3.        ],
       [41.73      , 35.35      ,  1.        ,  0.4845    ,  0.95325581,
         3.        ],
       ...,
       [59.05      , 54.98      ,  1.        ,  0.4062    ,  0.79325581,
         1.        ],
       [74.65      , 40.46      ,  0.        ,  0.3818    ,  1.2744186 ,
         1.        ],
       [44.68      , 52.24      ,  1.        ,  0.666     ,  0.77232558,
         3.        ]])

In [12]:
y

array([0., 1., 0., ..., 1., 1., 1.])

In [13]:
from sklearn.linear_model import LogisticRegression as LR
from sklearn.linear_model import RandomizedLogisticRegression as RLR

In [14]:
rlr = RLR()

D:\ruanjian\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class RandomizedLogisticRegression is deprecated; The class RandomizedLogisticRegression is deprecated in 0.19 and will be removed in 0.21.
  warnings.warn(msg, category=DeprecationWarning)


In [15]:
rlr.fit(X,y)

RandomizedLogisticRegression(C=1, fit_intercept=True, memory=None, n_jobs=1,
               n_resampling=200, normalize=True, pre_dispatch='3*n_jobs',
               random_state=None, sample_fraction=0.75, scaling=0.5,
               selection_threshold=0.25, tol=0.001, verbose=False)

In [16]:
rlr.get_support() # 获取有效特征

array([ True, False, False, False, False,  True])

In [17]:
index = df.loc[:,'x1':'x6'].columns[rlr.get_support()]

In [18]:
d_new = df.loc[:,'x1':'x6']

In [19]:
x = d_new[index]

In [20]:
lr = LR()

In [21]:
x.shape

(6329, 2)

In [22]:
y

array([0., 1., 0., ..., 1., 1., 1.])

In [23]:
y.shape

(6329,)

In [24]:
lr.fit(x,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [32]:
lr.coef_

array([[0.01624975, 0.00137513, 0.17131849, 0.03224617, 0.02890143,
        0.23974492]])

In [25]:
lr.score(x,y)

0.7819560752093537

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)
lr = LR()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.7820593809222994

In [27]:
df = pd.read_excel('D:/2018 广东金融学院数学建模第一次模拟(1)/2018 广东金融学院数学建模第一次模拟/附件1.xls')
df.head()

X = df.loc[:,'x1':'x6'].as_matrix()

D:\ruanjian\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  after removing the cwd from sys.path.


In [29]:
myPredict = lr.predict(X)

In [37]:
len(myPredict)

6330

In [36]:
for i in range(len(myPredict)):
    print("第"+str(i)+"个：" + str(myPredict[i])

SyntaxError: unexpected EOF while parsing (<ipython-input-36-86f0c1517eb6>, line 2)